const sendMessage=async(req,res,next)=>{
    try {
        
        

    } catch (error) {
        console.error(`error in send messages :: ${error.message}`)
        next(error)
    }
}

const deleteMessage=async(req,res,next)=>{
    try {

          

        
    } catch (error) {
        console.error(`error in delete messages :: ${error.message}`)
        next(error)
    }
}